Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/06/2022
Var
// Seção de Declarações das variáveis 
A, B, C: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
A <- 2
B <- 3
C <- 5
Escreva (nao(A>C) e (C=A+B))
Fimalgoritmo
